# build stage
FROM node:20-alpine AS build

WORKDIR /build

# Copier les fichiers nécessaires pour installer les dépendances
COPY package*.json ./

RUN npm install && npm cache clean --force

# Copier tout le code du backend
COPY . .

# production stage
FROM node:20-alpine

WORKDIR /app

# Copier node_modules depuis la build stage
COPY --from=build /build/node_modules ./node_modules

# Copier le reste de l'application
COPY --from=build /build/. .

EXPOSE 80

ENTRYPOINT [ "node", "server.js" ]
