# build stage
FROM node:20-alpine AS build

WORKDIR /build

COPY package*.json ./

RUN npm ci ; npm cache clean --force

# production stage
FROM node:20-alpine

WORKDIR /app

# 🔧 Correction : utiliser le chemin absolu
COPY --from=build /build/node_modules ./node_modules

# Copier tout le code de l'app
COPY . .

EXPOSE 80

ENTRYPOINT [ "node" , "server.js" ]
