# backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-pod
  template:
    metadata:
      labels:
        name: backend-pod
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
        - name : backend
          # use youre backend's docker image
          image: 645052660152.dkr.ecr.us-east-1.amazonaws.com/pfe-ecr:backend-pfe
          ports :
          - containerPort: 80
          env:
            - name: DATABASE
              value: "mongodb://admin:dwXJmJVrSvXpVUML@mongodb/mapApp?retryWrites=true&w=majority&appName=map-app&authSource=admin"
---
# backend service
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    name: backend-pod
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
       nodePort:30080
